---
- hosts: localhost
  vars_prompt:

    - name: user_name
      prompt: "What is your username?"
      private: no

    - name: pass_word
      prompt: "What is your password?"

  tasks:

    - debug:
        msg: 'Logging in as {{ user_name }} & Password is {{ pass_word }}'
