---
- name: This playbook will add nodes to the nagios-server for monitoring
  hosts: nagios-server

  vars:
    host_client:
      - "{{ inventory_hostname }}"
  
  tasks:

  - name: Copy nagios config file to import directory
    template:
      src: nagios-cfg.j2
      dest: /usr/local/nagios/etc/import/nagios.cfg
    with_items:
      - host_client

#  - name: Copy nagios.cfg file to import directory
#    copy:
#      src: nagios.cfg
#      dest: /usr/local/nagios/etc/import/nagios.cfg
#      owner: nagios
#      group: nagios
#      mode: 755

#  - name: Reconfigure nagios for client integration
#    command: /usr/local/nagiosxi/scripts/reconfigure_nagios.sh
#    args:
#      chdir: /usr/local/nagiosxi/scripts/

#  - name: Restart nagios on server to use new configuration
#    service:
#      name: nagios
#      state: restarted

