---
  - name: This playbook configures nagios client for SUSE OS family
    hosts: nodes

    vars:
      nagios_server: 192.168.56.11

    tasks:
      - name: Copy SUSE packages from nagios server to {{ansible_hostname}}
        local_action: command scp /root/myAnsible/nagios-play/NRPE-3.2.1-NewBuild.tar.gz root@{{inventory_hostname}}:/tmp/
        when: ansible_distribution == 'SuSE' or ansible_distribution == 'SLES'


      - name: Extract SuSE binaries to /tmp directory of SuSE client machines.
        unarchive:
          src: /tmp/NRPE-3.2.1-NewBuild.tar.gz
          dest: /tmp/
          remote_src: yes
        when: ansible_distribution == 'SuSE' or ansible_distribution == 'SLES'


      - name: Install RPMs in the SuSE client machine.
        command: "{{ item }} chdir=/tmp/NRPE-3.2.1-NewBuild/"
        with_items:
          - rpm -ivh monitoring-plugins-2.2-1.1.x86_64.rpm
          - rpm -ivh monitoring-plugins-all-2.2-1.1.x86_64.rpm
          - rpm -ivh monitoring-plugins-disk-2.2-1.1.x86_64.rpm
          - rpm -ivh monitoring-plugins-load-2.2-1.1.x86_64.rpm
          - rpm -ivh monitoring-plugins-procs-2.2-1.1.x86_64.rpm
          - rpm -ivh monitoring-plugins-users-2.2-1.1.x86_64.rpm
          - rpm -ivh monitoring-plugins-swap-2.2-1.1.x86_64.rpm
          - rpm -ivh monitoring-plugins-common-2.2-1.1.x86_64.rpm
          - rpm -ivh nrpe-3.2.1-9.1.x86_64.rpm
        when: ansible_distribution == 'SuSE' or ansible_distribution == 'SLES'  


      - name: Copy monitoring plugins from extraplugins dir to /usr/lib/nagios/plugins directory.
        command: cp -rf /tmp/NRPE-3.2.1-NewBuild/extraplugins/{{item}} /usr/lib/nagios/plugins/
        with_items:
          - check_cpu_stats.sh
          - check_init_service
          - check_netstat.pl
          - check_open_files.pl
          - check_services
          - custom_check_mem
          - custom_check_procs
        when: ansible_distribution == 'SuSE' or ansible_distribution == 'SLES' 


      - name: Add nagios server IP in client machine
        template:
          src: /root/myAnsible/nagios-play/nrpe-cfg.j2
          dest: /etc/nrpe.cfg
        when: ansible_distribution == 'SuSE' or ansible_distribution == 'SLES'


      - name: Create /run/nrpe directory and change ownership.
        file:
          path: /run/nrpe/
          state: directory
          owner: nagios
          group: nagios
        when: ansible_distribution == 'SuSE' or ansible_distribution == 'SLES'


      - name: Start and enable nrpe service
        service: name=nrpe state=started enabled=yes
        when: ansible_distribution == 'SuSE' or ansible_distribution == 'SLES'

#  - include: nagios-client.yml
#    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'



#https://stackoverflow.com/questions/21892603/how-to-make-ansible-execute-a-shell-script-if-a-package-is-not-installed
